# -*- coding: utf-8 -*-
"""EYEFATIGUE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10q3mXjqAegSMxynZcyeR-_z8vI2LRttd
"""

import numpy as np
import pandas as pd

# 1. DATA LOADING
data = []
with open('area(1).txt', 'r') as f:
    for line in f.readlines()[1:]:
        parts = line.split(',')
        if len(parts) == 2:
            area_val = float(parts[0].strip().split()[0])
            time_val = float(parts[1].strip())
            data.append([area_val, time_val])

df = pd.DataFrame(data, columns=['Area', 'Time'])
z = df['Area'].values
t = df['Time'].values
n = len(z)
dt = np.mean(np.diff(t))

# 2. TUNED INITIALIZATION
# R is the "trust" factor. Lower R = trust sensor more (less flat line).
R = 55.0
F = np.array([[1, dt], [0, 1]])
H = np.array([[1, 0]])

xf = np.zeros((n, 2))
Pf = np.zeros((n, 2, 2))
xp = np.zeros((n, 2))
Pp = np.zeros((n, 2, 2))

xf[0] = [z[0], 0]
Pf[0] = np.eye(2) * 1000

# 3. HIGH-SENSITIVITY FORWARD PASS
for k in range(1, n):
    xp[k] = F @ xf[k-1]

    # BIOLOGICAL TRIGGER
    # We check if the eye area moved more than 5 units.
    # If it did, we spike Q (q_val=1000) so the filter "jumps" to catch the blink.
    gap = abs(z[k] - xp[k, 0])
    q_val = 1000.0 if gap > 5.0 else 0.1

    Q = np.array([[dt**4/4, dt**3/2], [dt**3/2, dt**2]]) * q_val
    Pp[k] = F @ Pf[k-1] @ F.T + Q

    # Update logic
    S = H @ Pp[k] @ H.T + R
    K = Pp[k] @ H.T / S[0,0] # Kalman Gain

    xf[k] = xp[k] + K.flatten() * (z[k] - xp[k, 0])
    Pf[k] = (np.eye(2) - K @ H) @ Pp[k]

# 4. BACKWARD PASS (Zero-Phase Smoothing)
# This removes the "skewing" and "lag"
xs = np.copy(xf)
for k in range(n-2, -1, -1):
    C = Pf[k] @ F.T @ np.linalg.inv(Pp[k+1])
    xs[k] = xf[k] + C @ (xs[k+1] - xp[k+1])

# 5. CONSTRAINTS & CLEANUP
# clip(0, None) ensures no negative values
df['Clean_Area'] = np.clip(xs[:, 0], 0, None)

# Calculate Derivatives
df['Velocity'] = np.gradient(df['Clean_Area'], df['Time'])
df['Jerk'] = np.gradient(np.gradient(df['Velocity'], df['Time']), df['Time'])
df['Jerk_Var'] = df['Jerk'].rolling(window=20, center=True).var()

# 6. RESULTS
max_slope = df['Velocity'].min()
avg_jerk = df['Jerk_Var'].mean()

# Fatigue detection logic
if max_slope > -100 and avg_jerk > 500:
    result = "FATIGUED"
else:
    result = "ALERT"

print(f"--- Analysis Results ---")
print(f"Max Slope (Blink Speed): {max_slope:.2f}")
print(f"Jerk Variance (Tremor): {avg_jerk:.2f}")
print(f"Final Verdict: {result}")